export { default as GCPProjects } from './GCPProjects'
export { default as Dashboard } from './Dashboard'
export { default as ObjectStorages } from './ObjectStorages'
export { default as Users } from './Users'
export { default as VirtualMachines } from './VirtualMachines'
export { default as Development } from './Development'
